name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.6.0=py36h49b8c8c_1
  - numpy=1.14.3=py36hcd700cb_1
  - numpy-base=1.14.3=py36h9be14a7_1
  - numpydoc=0.8.0=py36_0
  - pandas=0.23.0=py36h637b7d7_0
  - requests=2.18.4=py36he2e5f8d_1

